FROM python:3.12-slim

WORKDIR /app

#Copy required files
COPY requirements.txt .
COPY graph.py .
COPY runner.py . 

#Install dependencies
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

#Command to run your custom application
CMD ["python", "runner.py"]



