FROM python:3.11-slim

WORKDIR /app

#Copy required files
COPY requirements.txt /app/
COPY src/__init__.py /app/src/
COPY src/inference.py /app/src/
COPY src/lambda_func.py /app/src/
COPY output/model/finetuned_model/ /app/model/

#Install dependencies
RUN pip install awslambdaric
RUN pip install -r requirements.txt

#Make script readable and execuatble
RUN chmod -R a+rX /app

#Set lambda function 
ENTRYPOINT ["/usr/local/bin/python", "-m", "awslambdaric"]
CMD ["src.lambda_func.lambda_function"]