#Get image
FROM rasa/rasa-sdk:3.6.2

WORKDIR /app

# Copy as root
COPY requirements.txt ./
COPY actions/ ./actions/

# Install dependencies as root
USER root
RUN pip install --no-cache-dir -r requirements.txt

# Switch to root to fix permissions
RUN chmod -R 755 /app

# Run actions server on 5055
EXPOSE 5055
